name: Build, Push and Deploy Blue Green

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t biku0786/fastapi-devops-demo:latest .

      - name: Push Docker image
        run: docker push biku0786/fastapi-devops-demo:latest

      - name: Deploy Smart Blue Green
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            sudo docker pull biku0786/fastapi-devops-demo:latest

            CURRENT_PORT=$(grep proxy_pass /etc/nginx/sites-available/default | sed -E 's/.*:([0-9]+);/\1/')

            if [ "$CURRENT_PORT" = "8000" ]; then
              NEW_PORT=8001
              NEW_NAME=fastapi-green
            else
              NEW_PORT=8000
              NEW_NAME=fastapi-blue
            fi

            sudo docker rm -f $NEW_NAME || true

            sudo docker run -d \
              --restart unless-stopped \
              --name $NEW_NAME \
              -p $NEW_PORT:8000 \
              -e DB_CONNECTION=postgresql+psycopg2://postgres:ratish0786@postgres-db:5432/mydb \
              -e SECRET_KEY=mysecretkey \
              -e ALGORITHM=HS256 \
              -e EXP_TIME=30 \
              --link postgres-db \
              biku0786/fastapi-devops-demo:latest

            sleep 10

            curl -f http://localhost:$NEW_PORT/health || exit 1

            sudo sed -i "s/$CURRENT_PORT/$NEW_PORT/g" /etc/nginx/sites-available/default
            sudo systemctl reload nginx